export const UI_TEXT = {
  promptPlaceholder: "Ask the model to write or change code...",
  chatHistoryTitle: "Chats",
  newChatButton: "New chat",
  chatHistoryButton: "Chats",
  hideChatHistoryButton: "Hide chats",
  chatHistoryTooltip: "Open chat history",
  hideChatHistoryTooltip: "Close chat history",
  renameChatButton: "Rename chat",
  renamePrompt: "Rename chat",
  emptyChatTooltip: "Send a message before starting a new chat",
  codeTitle: "Resources",
  resourcesButton: "Resources",
  hideResourcesButton: "Hide resources",
  resourcesTooltip: "Open resources panel",
  hideResourcesTooltip: "Close resources panel",
  loadingCode: "Loading generated code...",
  emptyCode: "No generated code blocks yet.",
  runButton: "Run Codex",
  emptyPromptTooltip: "Enter a message",
  running: "Running...",
  unexpectedError: "Unexpected error",
} as const;
